Homework-07
Otus-DevOps-2017-11/belykhva_infra pull request #3
Opened 2017-12-21 09:11 UTC by belykhva

All task was completed:
- common tasks
- both extra tasks

2017-12-22 19:56 UTC, vitkhab requested changes
Выполнено хорошо. Прошу:
- "починить" `variables.json`
- переименовать `variables.json` в `variables.json.example`
- внести `variables.json` в `.gitignore`

Из плюсов хочу отметить:
- Есть вся необходимая документация 
- Выполнены оба задания со звездочками. Молодец!

2017-12-22 19:56 UTC, vitkhab commented on packer/variables.json
> +    }
Лишняя скобка

2017-12-22 19:56 UTC, vitkhab commented on packer/variables.json
> +{
Хорошая практика - хранить пример конфигурации с расширением файла `.example`, например `variables.json.example`, а сам файл с настройками вносить в `.gitignore`.
Делается это для того, чтобы случайно не запушить актуальные настройки и не раскрыть потенциально чувствительные данные. И чтобы те, кто будут переиспользовать твой проект в явном виде указали нужные им настройки.

2017-12-22 19:56 UTC, vitkhab commented on packer/variables.json
> +    "tags": "testvm test app",
Тут я ожидаю валидное значение переменной.
А получаю ошибку `'testvm test app'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'`

2017-12-22 19:56 UTC, vitkhab commented on packer/ubuntu16.json
> +    "tags": "testvm test app",
Не валидное значение по умолчанию

2017-12-22 19:56 UTC, vitkhab commented on packer/immutable.json
> +    "image_name": "reddit-full-{{timestamp}}",
Хорошо бы синхронизировать `image_name` и `image_family`.
Если я поменяю `image_family` с `reddit-full` на  `reddit-baked`, например,  то получу две пачки образов с именем `reddit-full-*`. Это вносит немного хаоса в нашу систему.

2017-12-24 08:11 UTC, belykhva commented on packer/immutable.json
> +    "image_name": "reddit-full-{{timestamp}}",
Да, добавил переменную в имя образа! Спасибо.

2017-12-24 08:12 UTC, belykhva commented on packer/ubuntu16.json
> +    "tags": "testvm test app",
Да, упустил, столкнулся с этим, исправил в одном месте, но забыл сделать в другом. Спасибо, исправил.

2017-12-24 08:12 UTC, belykhva commented on packer/variables.json
> +{
Done.

2017-12-24 08:12 UTC, belykhva commented on packer/variables.json
> +    "tags": "testvm test app",
Done.

2017-12-24 08:12 UTC, belykhva commented on packer/variables.json
> +    }
Убрал, недоглядел. Спасибо!

2017-12-24 08:13 UTC, belykhva commented
Все баги исправлены.

2017-12-25 09:41 UTC, vitkhab commented
@belykhva все еще не валидный тег. Google выдает ошибку
```
Error creating instance: googleapi: Error 400: Invalid value for field 'resource.tags.items[0]': 'Sample tag'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

2017-12-25 10:25 UTC, belykhva commented
Пофиксил :) Исправил все, да не все :)

2017-12-27 10:05 UTC, vitkhab approved these changes

2017-12-28 09:28 UTC, merged